services:
  mongo:
    image: mongo
    container_name: mi_mongo
    volumes:
      - mongo-vol:/data/db
    networks:
      mongo-node-net:
        ipv4_address: 172.40.0.10
    expose:
      - 27017
  nodejs:
    build: .
    image: mi-node-image
    container_name: mi_node
    networks:
      mongo-node-net:
        ipv4_address: 172.40.0.11
      node-nginx-net:
        ipv4_address: 172.80.0.11
    expose:
      - 8080
  nginx:
    image: nginx
    networks:
      node-nginx-net:
        ipv4_address: 172.80.0.10
    ports:
      - 8081:80
    links:
      - nodejs
    environment:
      NGINX_HOST: mi_node

networks:
  mongo-node-net:
    ipam:
      config:
        - subnet: 172.40.0.0/16
  node-nginx-net:
    ipam:
      config:
        - subnet: 172.80.0.0/16

volumes:
  mongo-vol: