services:
  mongo:
    container_name: mi-mongo-composer
    image: mongo
    volumes:
      - mi-volumen:/data/db
    networks:
      - mi-red
  mongo-express:
    image: mongo-express
    networks:
      - mi-red
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mi-mongo-composer


volumes:
  mi-volumen:

networks:
  mi-red:
    driver: bridge